In [24]:
#Write a np program to create 3x3 matrix with values ranging from 2 to 10
import numpy as np
a =  np.arange(2, 11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [25]:
#wanpp to create  null vector of size 10 and update sixth value to 11
print("Original vector")
b = np.zeros(10)
print(b)
print("After updating sixth value to 11")
b[6] = 11
print(b)

Original vector
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After updating sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [26]:
#wanpp to reverse an array(first element becomes last)
c = np.arange(1, 11)
print("Original array:")
print(c)
print("After reversing the array:")
c = c[::-1]
print(c)

Original array:
[ 1  2  3  4  5  6  7  8  9 10]
After reversing the array:
[10  9  8  7  6  5  4  3  2  1]


In [27]:
#wanpp  to create a 2d array with 1 on the border and 0 inside
d = np.ones((4,4))
print("Original array:")
print(d)
print("After 1 on the border and 0 inside in the array")
d[1:-1,1:-1] = 0
print(d)

Original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
After 1 on the border and 0 inside in the array
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
